### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by jcroucher** [hawezo/laravel-boilerplate#7]
For anyone that has similar issues.
On running the install step `php artisan app:install` two errors occurred.

The first error `Class 'Faker\Factory' not found`

To fix `composer require fzaninotto/faker`

The second error was 

`Spatie\Permission\Exceptions\GuardDoesNotMatch: The given role or permission should use guard `` instead of `web`.`

To fix this I updated config/auth.php from

```
'providers' => [
        users' => [
            'driver' => env('LDAP_ENABLED', false) ? 'ldap' : 'eloquent',
            'model'  => User::class,
        ],
```

To

```
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
```

I also recommend changing in .env APP_DEBUG to true
and in routes Route::post('/logout') to Route::any('/logout')
That way /logout can be used from the browser to test different roles quickly before that side has been developed.

**Comment by hawezo** [comment]
Thanks! It's in my list of things I need to fix. I'm waiting for Laravel 7 to simplify a lot of this boilerplate's stuff.

**Comment by hawezo** [comment]
Thanks! It's in my list of things I need to fix. I'm waiting for Laravel 7 to simplify a lot of this boilerplate's stuff.

**Comment by hawezo** [comment]
I updated the boilerplate entirely to remove unnecessary functionalities, so this is now fixed.
